import PageHero from "@/components/PageHero";
import Link from "next/link";
import styles from "./page.module.css";

export default function PrivacyPage() {
  return (
    <>
      <PageHero title="Privacy Policy" />

      <section className={styles.contentSection}>
        <div className={styles.card}>
          <p className={styles.lastUpdated}>Last updated: February 2025</p>

          <h2>Overview</h2>
          <p>
            Body Insight operates medical-grade DEXA body composition scanning
            services across India. We are committed to protecting the privacy of
            your personal and health-related data. This policy explains what
            information we collect, how we use it, and your rights regarding that
            data.
          </p>

          <h2>Information We Collect</h2>
          <p>When you book a scan or use our services, we may collect:</p>
          <ul>
            <li>
              <strong>Personal information:</strong> Name, email address, phone
              number, date of birth, and gender.
            </li>
            <li>
              <strong>Body measurements:</strong> Height, weight, and data
              generated by your DEXA scan (body fat percentage, lean mass,
              visceral fat, bone density).
            </li>
            <li>
              <strong>Booking information:</strong> Appointment date, time,
              location, and payment details.
            </li>
            <li>
              <strong>Communications:</strong> Messages sent through our contact
              form or email.
            </li>
          </ul>

          <h2>How We Use Your Data</h2>
          <ul>
            <li>To process and confirm your scan bookings.</li>
            <li>
              To generate your personalised DEXA report with AI-powered
              insights.
            </li>
            <li>
              To send appointment confirmations, reminders, and your scan
              report.
            </li>
            <li>To respond to your enquiries and support requests.</li>
            <li>To improve our services and user experience.</li>
          </ul>

          <h2>Data Security</h2>
          <p>
            Your body composition data is sensitive and we treat it as such. We
            use encrypted connections, secure authentication (OTP-based login),
            and access controls to protect your information. Your scan data is
            only accessible to you and authorised Body Insight personnel.
          </p>

          <h2>Data Sharing</h2>
          <p>
            We do not sell, rent, or share your personal or health data with
            third parties for marketing purposes. We may share data only:
          </p>
          <ul>
            <li>With your explicit consent.</li>
            <li>
              With service providers who help us operate our platform (e.g.
              email delivery, cloud hosting), bound by confidentiality
              agreements.
            </li>
            <li>When required by law or legal proceedings.</li>
          </ul>

          <h2>Data Retention</h2>
          <p>
            We retain your scan data and reports so you can track your progress
            over time. You may request deletion of your data at any time by
            contacting us.
          </p>

          <h2>Your Rights</h2>
          <p>You have the right to:</p>
          <ul>
            <li>Access the personal data we hold about you.</li>
            <li>Request correction of inaccurate data.</li>
            <li>Request deletion of your data.</li>
            <li>Withdraw consent for communications at any time.</li>
          </ul>

          <h2>Contact</h2>
          <p>
            If you have questions about this privacy policy or your data, please{" "}
            <Link href="/contact">contact us</Link>.
          </p>
        </div>
      </section>
    </>
  );
}
